import os
import subprocess
from pathlib import Path

class WorldPainterInterface:
    def __init__(self, config={}):
        self.config = config

    def _to_wp_path(self, path):
        """Converts local path to an absolute string with forward slashes for JS."""
        return str(Path(path).resolve()).replace('\\', '/')

    def generate_script(self, heightmap_path, output_world_path, **kwargs):
        """Generates the WorldPainter Javascript to build the world."""
        mp = self.config.get('minecraft', {})
        scale = mp.get('scale', {}).get('scale_percent', 100) if isinstance(mp.get('scale'), dict) else 100
        
        abs_hm = self._to_wp_path(heightmap_path)
        abs_out = self._to_wp_path(output_world_path)
        
        # Build JS lines
        lines = [
            "// Auto-generated by map2craft",
            f"print('Heightmap: {abs_hm}');",
            f"var heightMap = wp.getHeightMap().fromFile('{abs_hm}').go();",
            f"var mapFormat = wp.getMapFormat().withId('org.pepsoft.anvil.{mp['version']}').go();",
            f"var world = wp.createWorld().fromHeightMap(heightMap).scale({scale})",
            f"    .fromLevels(0, 65535).toLevels({mp['build_limit']['min']}, {mp['build_limit']['max']})",
            f"    .withWaterLevel({mp['sea_level']}).withMapFormat(mapFormat)",
            f"    .withLowerBuildLimit({mp['build_limit']['min']})",
            f"    .withUpperBuildLimit({mp['build_limit']['max']}).go();"
        ]

        # Conditional layers (Placeholders for future enhancements)
        for key in ['water_mask', 'slope_mask']:
            if kwargs.get(key):
                lines.append(f"print('Applying {key}...');")
                lines.append(f"var {key} = wp.getHeightMap().fromFile('{self._to_wp_path(kwargs[key])}').go();")

        lines.extend([
            f"wp.saveWorld(world).toFile('{abs_out}').go();",
            "print('Done!');"
        ])
        
        return "\n".join(lines)

    def run_worldpainter(self, script_path):
        """Executes the WorldPainter JS script via wpscript executable."""
        wp_dir = self.config.get('worldpainter', {}).get('path', '')
        exe = Path(wp_dir)/'wpscript.exe' if os.name == 'nt' else Path('wpscript')
        
        # Fallback to system PATH if config path is invalid
        cmd = [str(exe) if exe.exists() else 'wpscript', script_path]
        
        print(f"Running WorldPainter: {cmd[0]}")
        try:
            subprocess.run(cmd, check=True)
        except (FileNotFoundError, subprocess.CalledProcessError) as e:
            print(f"WorldPainter execution failed: {e}")
            raise

    def world_action(self, target, source, env):
        """SCons action for world generation."""
        # source: [heightmap, metadata, water, slope, biome(opt)]
        script_content = self.generate_script(
            source[0], target[0],
            metadata_file=source[1],
            water_mask=source[2],
            slope_mask=source[3],
            biome_map=source[4] if len(source) > 4 else None
        )
        
        Path(str(target[1])).write_text(script_content)
        self.run_worldpainter(str(target[1]))

    def export_action(self, target, source, env):
        """SCons action to export .world file to Minecraft save directory."""
        world_path = self._to_wp_path(source[0])
        out_dir = self._to_wp_path(Path(str(target[0])).parent)
        script_path = Path(str(target[0])).parent / "export_script.js"

        script = (
            f"var world = wp.getWorld().fromFile('{world_path}').go();\n"
            f"wp.exportWorld(world).toDirectory('{out_dir}').go();\n"
            "print('Export complete!');"
        )
        
        script_path.write_text(script)
        self.run_worldpainter(str(script_path))
    